#!/bin/sh

for device in /dev/sd*1
do
    mount $device /mnt
    if [ -d /mnt/tempmanager/ ]; then
        cp -rf /mnt/tempmanager /tmp
        umount $device

        cd /tmp/tempmanager
        qmake -qt=5

        make -j4

        if [ ! $? -eq 0 ]; then
            exit 2
        fi

        mv tempmanager /usr/local/bin

        exit 0
    else
        umount $device
    fi
done

#if rpi-update | grep -q 'A reboot is needed'; then
#   exit 0
#else
   exit 1
#fi
